### ISSUE TITLE
Indentation of lines with preprocessor directives

### ISSUE THREAD

**Issue by athmargaritis** [rudrab/vimf90#7]
Hello, I am using this plugin and find it quite useful for writing fortran code. 

I am having an issue with lines that include preprocessor directives (starting with `#` such as `#IFDEF VARIABLE`  ... `#ENDIF`) in *.f90 files.

When I save the file the whole file is formatted and indented (correctly). However, lines with preprocessor directives are also indented like normal lines which creates problems with compilers (these lines should remain at the first column, otherwise they are not accepted). Basically they need to either be ignored during indentation (but retain the indentation level for next line) or be fixed after indentation is completed.

Is this the intended behaviour or is it some conflict or other setting in my setup? If it is the intended behaviour, is there a way to avoid it? I removed the plugin and the problem disappears, so I assume it comes from vimf90. I appreciate any help

I am using nvim 0.4.3. Please let me know if you need any more version info etc. Thanks a lot!

**Comment by rudrab** [comment]
hi, 
Thanks a lot for reporting the issue. It is due to the fact that the doc/readme is not well written (Sorry for that!).
I am assuming your vim is compiled with python3  (check with `vim --version`). 

Now, install `fprettify` as: `pip3 install fprettify --user`
and in `~/.vimrc`, `set: g:VimF90Linter = 2`

You will probably get the indent properly.

**Comment by athmargaritis** [comment]
Thanks a lot for the prompt response. Indeed, these steps fixed the issue.
